/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./scene.gltf 
*/

import React, {forwardRef, useEffect, useRef} from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'

export const Lewis = forwardRef(function Lewis(props, ref) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/lewis/scene.gltf`)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    props.setAnimationActions(actions);
  }, [actions]);

  return (
      <group ref={group} {...props} dispose={null}>
        <group ref={ref} name="Scene">
          <group name="Armature003" rotation={[Math.PI / 2, 0, Math.PI]} scale={0.011}>
            <primitive object={nodes.mixamorig4Hips} />
            <group name="Ch12">
              <skinnedMesh
                  name="Mesh"
                  geometry={nodes.Mesh.geometry}
                  material={materials.Ch12_body}
                  skeleton={nodes.Mesh.skeleton}
              />
              <skinnedMesh
                  name="Mesh_1"
                  geometry={nodes.Mesh_1.geometry}
                  material={materials.Ch12_hair}
                  skeleton={nodes.Mesh_1.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
  )
})

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/lewis/scene.gltf`)
