/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./scene.gltf 
*/

import React, {forwardRef, useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export const Mousey = forwardRef(function Mousey(props, ref) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/mousey/scene.gltf`)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    props.setAnimationActions(actions);
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group ref={ref} name="Scene">
        <group name="Armature003" rotation={[Math.PI / 2, 0, Math.PI]} scale={0.013}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch14" geometry={nodes.Ch14.geometry} material={materials.Ch14_Body} skeleton={nodes.Ch14.skeleton} />
        </group>
      </group>
    </group>
  )
});

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/mousey/scene.gltf`)
