/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./scene.gltf 
*/

import React, {forwardRef, useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export const Prisoner = forwardRef(function Prisoner(props, ref) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/prisoner/scene.gltf`)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    props.setAnimationActions(actions);
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group ref={ref} name="Scene">
        <group name="Armature003" position={[0.026, -0.006, 0.003]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Prisoner" geometry={nodes.Prisoner.geometry} material={materials.Prisoner_material} skeleton={nodes.Prisoner.skeleton} />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/prisoner/scene.gltf`)
