/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
*/

import React, {forwardRef, useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export const SportyGranny = forwardRef(function SportyGranny(props, ref) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/sporty_granny/scene.gltf`)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    props.setAnimationActions(actions);
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group ref={ref} name="Scene">
        <group name="Armature002" position={[0.011, -0.011, 0.002]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.011}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Fitness_Grandma_BodyGeo">
            <skinnedMesh name="Fitness_Grandma_BodyGeo_1" geometry={nodes.Fitness_Grandma_BodyGeo_1.geometry} material={materials.Grandma_MAT} skeleton={nodes.Fitness_Grandma_BodyGeo_1.skeleton} />
            <skinnedMesh name="Fitness_Grandma_BodyGeo_2" geometry={nodes.Fitness_Grandma_BodyGeo_2.geometry} material={materials.Lens_MAT} skeleton={nodes.Fitness_Grandma_BodyGeo_2.skeleton} />
          </group>
          <skinnedMesh name="Fitness_Grandma_BrowsAnimGeo" geometry={nodes.Fitness_Grandma_BrowsAnimGeo.geometry} material={materials.FitGrandma_Brows_MAT1} skeleton={nodes.Fitness_Grandma_BrowsAnimGeo.skeleton} />
          <skinnedMesh name="Fitness_Grandma_EyesAnimGeo" geometry={nodes.Fitness_Grandma_EyesAnimGeo.geometry} material={materials.FitGrandma_Eyes_MAT1} skeleton={nodes.Fitness_Grandma_EyesAnimGeo.skeleton} />
          <skinnedMesh name="Fitness_Grandma_MouthAnimGeo" geometry={nodes.Fitness_Grandma_MouthAnimGeo.geometry} material={materials.FitGrandma_Mouth_MAT1} skeleton={nodes.Fitness_Grandma_MouthAnimGeo.skeleton} />
        </group>
      </group>
    </group>
  )
});

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/avatars/sporty_granny/scene.gltf`)
