ARG NODE_VERSION=21.1.0
FROM node:${NODE_VERSION}-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:${NODE_VERSION}-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_BASE_PATH
ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_SERVER_URL
ARG NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_RECONNECTION_DELAY
ARG NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_INCOMING_HEARTBEAT
ARG NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_OUTGOING_HEARTBEAT

ENV NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_SERVER_URL=$NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_SERVER_URL
ENV NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_RECONNECTION_DELAY=$NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_RECONNECTION_DELAY
ENV NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_INCOMING_HEARTBEAT=$NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_INCOMING_HEARTBEAT
ENV NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_OUTGOING_HEARTBEAT=$NEXT_PUBLIC_WEBSOCKET_NOTIFICATIONS_OUTGOING_HEARTBEAT
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM alpine:3.20.2 AS runner
WORKDIR /app

RUN apk add --no-cache nodejs

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

ENV PORT=3000

CMD ["node", "server.js"]
