/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: RunemarkStudio (https://sketchfab.com/runemarkstudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-cloud-f31be54812a348df86d94171098dae19
Title: Cartoon Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Cloud = (props) => {
  const { nodes, materials } = useGLTF("/models/cartoon_cloud/scene.gltf")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload("/models/cartoon_cloud/scene.gltf")
