/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
*/

import React, {forwardRef} from 'react'
import { useGLTF } from '@react-three/drei'

export const DetectiveOfficeWithWindow = forwardRef((props, ref) => {
    const { nodes, materials } = useGLTF("/models/detective_office_with_window/scene.gltf")
    return (
        <group {...props} ref={ref} dispose={null}>
            <group position={[2.048, 1.907, 0.492]} rotation={[Math.PI / 2, 0, -0.941]} scale={[0.005, 0.086, 0.005]}>
                <mesh geometry={nodes.Object_36.geometry} material={materials.dark_metal} />
                <mesh geometry={nodes.Object_37.geometry} material={materials.glass} />
            </group>
            <mesh geometry={nodes.Object_30.geometry} material={materials.grey_metal} position={[0.861, 1.763, -4.587]} />
            <mesh geometry={nodes.Object_61.geometry} material={materials.book} position={[4.091, 2.589, -3.931]} scale={[1.997, 2.619, 1]} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.book} position={[3.373, 2.046, -3.337]} rotation={[0, 0, -Math.PI / 2]} scale={[1.34, 1.757, 0.671]} />
            <mesh geometry={nodes.Object_65.geometry} material={materials.book} position={[2.683, 2.046, -3.337]} rotation={[0, 0, -Math.PI / 2]} scale={[1.34, 1.757, 0.671]} />
            <mesh geometry={nodes.Object_67.geometry} material={materials.book} position={[1.862, 5.772, -3.931]} scale={[1.997, 2.619, 1]} />
            <mesh geometry={nodes.Object_69.geometry} material={materials.book} position={[-0.093, 3.032, -3.337]} scale={[1.635, 2.143, 0.818]} />
            <mesh geometry={nodes.Object_71.geometry} material={materials.book} position={[2.777, 4.152, -3.337]} rotation={[0, 0, -0.221]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_73.geometry} material={materials.book} position={[2.963, 4.152, -3.337]} rotation={[0, 0, -0.221]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_75.geometry} material={materials.book} position={[3.157, 4.152, -3.337]} rotation={[0, 0, -0.221]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_77.geometry} material={materials.book} position={[3.376, 4.152, -3.337]} rotation={[0, 0, -0.221]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_79.geometry} material={materials.book} position={[1.854, 0.989, -3.337]} rotation={[0, 0, -0.221]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_81.geometry} material={materials.book} position={[2.039, 0.989, -3.337]} rotation={[0, 0, -0.221]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_83.geometry} material={materials.book} position={[0.694, 3.065, -3.337]} rotation={[0, 0, 0.534]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_85.geometry} material={materials.book} position={[0.916, 3.073, -3.337]} rotation={[0, 0, 0.534]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_87.geometry} material={materials.book} position={[1.147, 3.069, -3.337]} rotation={[0, 0, 0.534]} scale={[1.915, 2.51, 0.959]} />
            <mesh geometry={nodes.Object_59.geometry} material={materials.book} position={[1.873, 2.589, -3.931]} scale={[1.997, 2.619, 1]} />
            <mesh geometry={nodes.Object_4.geometry} material={materials.bookshelf} position={[1.873, 2.589, -3.931]} scale={[1.997, 2.619, 1]} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.chair_wood} position={[3.287, 0.564, 1.213]} rotation={[0, 0.709, 0]} scale={0.052} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.drawers} position={[-2.457, 2.008, -4.443]} scale={[1.132, 1.172, 0.683]} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.glass_glass} position={[0.861, 1.763, -4.587]} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.grey_metal} position={[5.027, 5.813, 0.91]} scale={[0.033, 0.107, 1]} />
            <mesh
                geometry={nodes.Object_25.geometry}
                material={materials.green_metal}
                position={[0.861, 1.763, -4.587]}
                onClick={props.onClickLamp}
            />
            <mesh
                name={"double-paper-on-table"}
                geometry={nodes.Object_8.geometry}
                material={materials.paper}
                position={[0.861, 1.763, -4.587]}
                onClick={props.onDoublePaperClick}
            />
            <mesh geometry={nodes.Object_43.geometry} material={materials.dark_wood} position={[-3.09, 2.773, -3.675]} rotation={[0, -1.571, 0]} scale={1.123} />
            <mesh geometry={nodes.Object_45.geometry} material={materials.dark_wood} position={[-1.709, 2.773, -3.675]} rotation={[0, -1.571, 0]} scale={1.123} />
            <mesh geometry={nodes.Object_47.geometry} material={materials.dark_wood} position={[-1.709, 2.773, -3.675]} rotation={[0, -1.571, 0]} scale={1.123} />
            <mesh geometry={nodes.Object_49.geometry} material={materials.dark_wood} position={[-3.09, 2.097, -3.675]} rotation={[0, -1.571, 0]} scale={1.123} />
            <mesh geometry={nodes.Object_51.geometry} material={materials.dark_wood} position={[-1.709, 2.097, -3.675]} rotation={[0, -1.571, 0]} scale={1.123} />
            <mesh geometry={nodes.Object_53.geometry} material={materials.dark_wood} position={[-3.09, 1.018, -3.675]} rotation={[0, -1.571, 0]} scale={1.123} />
            <mesh geometry={nodes.Object_55.geometry} material={materials.dark_wood} position={[-1.709, 1.018, -3.675]} rotation={[0, -1.571, 0]} scale={1.123} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.dark_wood} position={[1.93, 1.143, 1.002]} />
            <mesh geometry={nodes.Object_39.geometry} material={materials.liquor} position={[1.862, 1.92, 1.865]} scale={[0.065, 0.021, 0.067]} />
            <mesh geometry={nodes.Object_34.geometry} material={materials.dark_wood} scale={5.199} />
        </group>
    )
});

useGLTF.preload("/models/detective_office_with_window/scene.gltf")
