/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: inter_net (https://sketchfab.com/inter_net)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-cff75ad8be4a4974a7792a5ae7142e30
Title: Door
*/

import React, {forwardRef, useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export const ExitDoor = forwardRef(function ExitDoor(props, ref) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/exit_door/scene.gltf`)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        props.setAnimationActions(actions);
    }, []);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene" ref={ref}>
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.843}>
                    <group name="Root">
                        <group name="Door_" position={[0, 0, 1.305]}>
                            <group name="Door_mechanism" position={[-0.592, -0.043, 0.016]}>
                                <group name="Handle" position={[1.096, 0.045, 0.002]}>
                                    <mesh name="Handle_0" geometry={nodes.Handle_0.geometry} material={materials.Door_1_PBR} />
                                </group>
                                <mesh name="Door_mechanism_0" geometry={nodes.Door_mechanism_0.geometry} material={materials.Door_1_PBR} />
                            </group>
                            <mesh name="Door__0" geometry={nodes.Door__0.geometry} material={materials.Door_1_PBR} />
                        </group>
                        <group name="Door_001" position={[0, 0.002, 1.305]} />
                        <group name="Door_004" position={[0, 0.002, 1.305]} />
                        <group name="Door_005" position={[0, 0.002, 1.305]} />
                        <group name="Door_006" position={[0, 0.002, 1.305]} />
                        <group name="Door_008" position={[0, 0.002, 1.305]} />
                    </group>
                </group>
            </group>
        </group>
    )
});

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/exit_door/scene.gltf`)
