/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: baby_silk (https://sketchfab.com/baby_silk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-class-room-3368e91fa2a8404996b81244036be4ee
Title: A class Room
*/

import React, {forwardRef, useRef} from 'react'
import { useGLTF } from '@react-three/drei'

export const GreenBoardWithTable = forwardRef((props, ref) => {
    const { nodes, materials } = useGLTF("/models/green_board_with_table/scene.gltf")
    return (
        <group ref={ref} {...props} dispose={null}>
            <mesh
                geometry={nodes.node_id38_Material_101_0.geometry}
                position={[-0.152, -0.074, 0.184]}
                onClick={props.onClickGreenBoard}
                material={materials.Material_101}
                scale={0.017}
            />
            {/*<mesh geometry={nodes.node_id44_Material_160_0.geometry} material={materials.Material_160} position={[-0.331, 0.239, 0.19]} scale={0.003} />*/}
            <mesh geometry={nodes.node_id50_Material_121_0.geometry} material={materials.Material_121} position={[0.202, -0.081, 0.643]} scale={0.045} />
            <mesh geometry={nodes.node_id56_Material_131_0.geometry} material={materials.Material_131} position={[0.376, 0.143, 0.649]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.006} />
            <mesh
                geometry={nodes.node_id76_Material_149_0.geometry}
                material={materials.Material_149}
                position={[0.175, 0.168, 0.734]}
                rotation={[Math.PI / 2, 0.163, -Math.PI]}
                scale={0.047}
                onClick={props.onClickFolder}
            />
        </group>
    )
})

useGLTF.preload("/models/green_board_with_table/scene.gltf")
