/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
*/

import React, {forwardRef} from 'react'
import {useGLTF} from '@react-three/drei'

export const HallWayWall = forwardRef(function HallWayWall(props, ref) {
    const { nodes, materials } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/hallway_wall/scene.gltf`)
    return (
        <group {...props} ref={ref} dispose={null}>
            <group scale={0.025} rotation-y={Math.PI}>
                <mesh geometry={nodes.Lamp_TrimSheet_0.geometry} material={materials.TrimSheet} />
                <mesh geometry={nodes.Wall_TrimSheet_0.geometry} material={materials.TrimSheet} />
                <mesh geometry={nodes.Wall_Wall_Mat_0.geometry} material={materials.Wall_Mat} />
            </group>
        </group>
    )
});

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/hallway_wall/scene.gltf`)
