/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: Kelisei Ventura (https://sketchfab.com/frankestudios71)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-set-lite-low-poly-ef6124dfbaf94365a76a6c1d613153d6
Title: Office Set Lite Low-poly
*/

import React, {forwardRef} from 'react'
import { useGLTF } from '@react-three/drei'

export const OfficeTableWithLaptop = forwardRef(function OfficeTableWithLaptop(props, ref) {
  const { nodes, materials } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/office_table_with_laptop/scene.gltf`)
  return (
      <group {...props} dispose={null}>
        <group scale={0.01} ref={ref}>
          <mesh geometry={nodes.Cube002_Table_0.geometry} material={materials.Table} position={[0.027, 6.095, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube004_Bin_0.geometry} material={materials.material} position={[16.488, 0.686, 7.635]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Computer_Computer_0.geometry} material={materials.Computer} position={[10.997, 11.579, 7.342]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder_Mug_0.geometry} material={materials.material_3} position={[14.424, 11.018, 9]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Chair_Chair_0.geometry} material={materials.Chair} position={[11.008, 5.154, 14.111]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
  )
})

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/office_table_with_laptop/scene.gltf`)
