/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
*/

import React, {forwardRef} from 'react'
import { useGLTF } from '@react-three/drei'

export const OldStyleOffice = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/old_style_office/scene.gltf")
  return (
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials.material_15} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Pencil} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.PinBoard} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Shelf01} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Shelf02} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Shelf03} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Stool} position={[1.474, 1.991, 0]} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Table} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Telephone} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Walls} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.Water_Cooler} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Big_Bottle} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.Big_Bottle} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.File01} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.File02} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.File03} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Cactus} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.File04} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.File_Stack} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.Paper03} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Paper_Cup} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.Paper_Stack} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.material_24} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Drawer} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.File_Stand} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.File_Storage} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Keyboard} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Lamp} />
          <mesh
              name={"monitor"}
              geometry={nodes.Object_9.geometry}
              material={materials.Monitor}
              onClick={props.onClickMonitor}
          />
        </group>
      </group>
  )
});

useGLTF.preload("/models/old_style_office/scene.gltf")
