/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: cloud (https://sketchfab.com/cloudstormchnl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mario-question-block-261331ee4e494fdcab69365dc61f33ba
Title: Mario Question Block
*/

import React, {forwardRef, useRef} from 'react'
import { useGLTF } from '@react-three/drei'

// eslint-disable-next-line react/display-name
export const QuestionBox = forwardRef((props, ref) => {
    const { nodes, materials } = useGLTF("/models/question_box/scene.gltf")
    return (
    <group ref={ref} dispose={null} rotation={[-Math.PI / 2, 0, 0]}  scale={0.121} {...props}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material}/>
        <mesh geometry={nodes.Object_3.geometry} material={materials.outline}/>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']}/>
    </group>
)
})

useGLTF.preload("/models/question_box/scene.gltf")
