/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\running-girl.gltf 
*/

import React, {useRef, useEffect, forwardRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import {playAllAnimationActions} from "@/helpers/animations";

// eslint-disable-next-line react/display-name
export const RunningGirl = forwardRef((props, ref) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/girl/running-girl.gltf`)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    playAllAnimationActions(actions);
    // if (props.isAnimationPlaying) {
    //   playAllAnimationActions(actions);
    //   return;
    // }
    // stopAllAnimationActions(actions);
  }, [props.isAnimationPlaying]);

  return (
      <group ref={group} {...props}>
        <group name="Scene" ref={ref} castShadow={true}>
          <group name="Armature" rotation={[Math.PI / 2, 0, Math.PI]} scale={0.01}>
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh name="Ch03" geometry={nodes.Ch03.geometry} material={materials.Ch03_Body} skeleton={nodes.Ch03.skeleton} />
          </group>
        </group>
      </group>
  )
})

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/girl/running-girl.gltf`)
