/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: GrillPork (https://sketchfab.com/GrillPork)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/safe-box-24e05336dc3740a1af9946b088049d19
Title: Safe box
*/

import React, {forwardRef} from 'react'
import { useGLTF } from '@react-three/drei'

export const SimpleSafeBox = forwardRef(function SimpleSafeBox(props, ref) {
  const { nodes, materials } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/simple_safe_box/scene.gltf`)
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.box_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder11_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube2_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder11_lambert1_0_1.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube2_lambert1_0_1.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface2_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder3_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder4_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder2_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder7_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder9_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder8_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder6_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder10_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder5_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube1_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube3_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
});

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/simple_safe_box/scene.gltf`)
