/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: padmadev2005 (https://sketchfab.com/padmadev20051)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-with-things-e39f2e1a7af240da8403fee1e93bc81f
Title: table with things
*/

import React, {forwardRef} from 'react'
import { useGLTF } from '@react-three/drei'

export const TableWithBooksAndGlobe = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/table_with_books_and_globe/scene.gltf")
  return (
      <group {...props} ref={ref} dispose={null}>
          <group scale={0.01}>
              <group position={[0, 225.395, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[253.196, 148.534, 22.642]}>
                  <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']}/>
                  <mesh geometry={nodes.Cube_Material012_0.geometry} material={materials['Material.012']}/>
                  <mesh geometry={nodes.Cube_Material025_0.geometry} material={materials['Material.025']}/>
                  <mesh geometry={nodes.Cube_Material013_0.geometry} material={materials['Material.013']}/>
                  <mesh geometry={nodes.Cube_Material011_0.geometry} material={materials['Material.011']}/>
                  <mesh geometry={nodes.Cube_Material093_0.geometry} material={materials['Material.093']}/>
              </group>
              <group position={[193.247, 256.282, 50.751]} rotation={[-Math.PI / 2, 0, -0.209]}
                     scale={[34.583, 41.801, 8.58]}>
                  <mesh geometry={nodes.Cube046_Material014_0.geometry} material={materials['Material.014']}/>
                  <mesh geometry={nodes.Cube046_Material015_0.geometry} material={materials['Material.015']}/>
              </group>
              <group
                  position={[-0.012, 289.087, -93.353]}
                  rotation={[-2.49, 0, 0]}
                  scale={[42.026, 37.497, 18.868]}
                  onClick={props.onClickBookOnTable}
              >
                  <mesh geometry={nodes.Cube050_Material037_0.geometry} material={materials['Material.037']}/>
                  <mesh geometry={nodes.Cube050_Material038_0.geometry} material={materials['Material.038']}/>
              </group>
              <group position={[190.481, 144.334, -157.459]} rotation={[-1.585, -0.071, -1.749]}
                     scale={[25.625, 30.974, 6.358]}>
                  <mesh geometry={nodes.Cube052_Material023_0.geometry} material={materials['Material.023']}/>
                  <mesh geometry={nodes.Cube052_Material024_0.geometry} material={materials['Material.024']}/>
              </group>
              <group position={[193.247, 273.818, 50.751]} rotation={[-Math.PI / 2, 0, 0.272]}
                     scale={[34.583, 41.801, 8.58]}>
                  <mesh geometry={nodes.Cube053_Material017_0.geometry} material={materials['Material.017']}/>
                  <mesh geometry={nodes.Cube053_Material018_0.geometry} material={materials['Material.018']}/>
              </group>
              <group position={[186.334, 255.728, -60.477]} rotation={[-Math.PI / 2, 0, -2.025]}
                     scale={[34.583, 41.801, 8.58]}>
                  <mesh geometry={nodes.Cube054_Material019_0.geometry} material={materials['Material.019']}/>
                  <mesh geometry={nodes.Cube054_Material020_0.geometry} material={materials['Material.020']}/>
              </group>
              <group position={[126.148, 268.711, -20.401]} rotation={[-1.542, -0.281, -1.445]}
                     scale={[34.583, 41.801, 8.58]}>
                  <mesh geometry={nodes.Cube055_Material021_0.geometry} material={materials['Material.021']}/>
                  <mesh geometry={nodes.Cube055_Material022_0.geometry} material={materials['Material.022']}/>
              </group>
              <group position={[-97.339, 250.159, -81.517]} rotation={[-Math.PI / 2, 0, 0.52]}
                     scale={[2.938, 11.926, 2.317]}>
                  <mesh geometry={nodes.Cube056_Material033_0.geometry} material={materials['Material.033']}/>
                  <mesh geometry={nodes.Cube056_Material034_0.geometry} material={materials['Material.034']}/>
                  <mesh geometry={nodes.Cube056_Material035_0.geometry} material={materials['Material.035']}/>
              </group>
              <mesh geometry={nodes.Cube001_Material010_0.geometry} material={materials['Material.010']}
                    position={[-190.481, 100.036, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 18.39]}/>
              <mesh geometry={nodes.Cube002_Material009_0.geometry} material={materials['Material.009']}
                    position={[-190.481, 140.14, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 18.39]}/>
              <mesh geometry={nodes.Cube003_Material008_0.geometry} material={materials['Material.008']}
                    position={[-190.481, 180.437, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 18.39]}/>
              <mesh geometry={nodes.Cube004_Material003_0.geometry} material={materials['Material.003']}
                    position={[189.751, 180.437, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 18.39]}/>
              <mesh geometry={nodes.Cube005_Material004_0.geometry} material={materials['Material.004']}
                    position={[189.751, 140.14, -189.821]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 18.39]}/>
              <mesh geometry={nodes.Cube006_Material005_0.geometry} material={materials['Material.005']}
                    position={[189.751, 100.036, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 18.39]}/>
              <mesh geometry={nodes.Cube007_Material007_0.geometry} material={materials['Material.007']}
                    position={[-190.481, 221.293, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 12.438]}/>
              <mesh geometry={nodes.Cube008_Material002_0.geometry} material={materials['Material.002']}
                    position={[189.751, 221.293, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[53.036, 2.827, 12.438]}/>
              <mesh geometry={nodes.Cube009_Material006_0.geometry} material={materials['Material.006']}
                    position={[0.253, 221.293, -149.331]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[127.053, 2.827, 12.438]}/>
              <mesh geometry={nodes.Cube010_Material092_0.geometry} material={materials['Material.092']}
                    position={[-190.799, 110.985, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube012_Material065_0.geometry} material={materials['Material.065']}
                    position={[-190.966, 95.75, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube013_Material064_0.geometry} material={materials['Material.064']}
                    position={[-190.966, 135.525, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube015_Material091_0.geometry} material={materials['Material.091']}
                    position={[-190.799, 150.76, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube016_Material090_0.geometry} material={materials['Material.090']}
                    position={[-190.799, 191.604, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube018_Material063_0.geometry} material={materials['Material.063']}
                    position={[-190.966, 176.369, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube019_Material059_0.geometry} material={materials['Material.059']}
                    position={[189.054, 176.369, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube020_Material078_0.geometry} material={materials['Material.078']}
                    position={[197.831, 180.194, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube021_Material085_0.geometry} material={materials['Material.085']}
                    position={[189.221, 191.604, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube022_Material084_0.geometry} material={materials['Material.084']}
                    position={[189.221, 150.76, -189.36]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube024_Material058_0.geometry} material={materials['Material.058']}
                    position={[189.054, 135.525, -196.708]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube025_Material057_0.geometry} material={materials['Material.057']}
                    position={[189.054, 95.75, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube027_Material086_0.geometry} material={materials['Material.086']}
                    position={[189.221, 110.985, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube028_Material087_0.geometry} material={materials['Material.087']}
                    position={[189.221, 228.218, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube030_Material060_0.geometry} material={materials['Material.060']}
                    position={[189.054, 216.539, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube031_Material062_0.geometry} material={materials['Material.062']}
                    position={[-190.657, 216.539, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube033_Material089_0.geometry} material={materials['Material.089']}
                    position={[-190.49, 228.218, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube034_Material088_0.geometry} material={materials['Material.088']}
                    position={[0.312, 228.218, -148.869]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[5.865, 4.064, 2.975]}/>
              <mesh geometry={nodes.Cube036_Material061_0.geometry} material={materials['Material.061']}
                    position={[0.144, 216.539, -156.218]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[9.768, 1.346, 1.391]}/>
              <mesh geometry={nodes.Cube037_Material079_0.geometry} material={materials['Material.079']}
                    position={[180.327, 180.194, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube011_Material080_0.geometry} material={materials['Material.080']}
                    position={[180.327, 139.316, -191.988]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube014_Material081_0.geometry} material={materials['Material.081']}
                    position={[197.831, 139.316, -191.988]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube017_Material083_0.geometry} material={materials['Material.083']}
                    position={[197.831, 99.45, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube023_Material082_0.geometry} material={materials['Material.082']}
                    position={[180.327, 99.45, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube026_Material076_0.geometry} material={materials['Material.076']}
                    position={[180.327, 220.152, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube029_Material077_0.geometry} material={materials['Material.077']}
                    position={[197.831, 220.152, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube032_Material074_0.geometry} material={materials['Material.074']}
                    position={[8.976, 220.152, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube035_Material075_0.geometry} material={materials['Material.075']}
                    position={[-8.527, 220.152, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube038_Material073_0.geometry} material={materials['Material.073']}
                    position={[-199.449, 220.152, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube039_Material072_0.geometry} material={materials['Material.072']}
                    position={[-181.945, 220.152, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube040_Material070_0.geometry} material={materials['Material.070']}
                    position={[-182.17, 180.061, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube041_Material071_0.geometry} material={materials['Material.071']}
                    position={[-199.673, 180.061, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube042_Material069_0.geometry} material={materials['Material.069']}
                    position={[-199.673, 139.183, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube043_Material068_0.geometry} material={materials['Material.068']}
                    position={[-182.17, 139.183, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube044_Material066_0.geometry} material={materials['Material.066']}
                    position={[-182.17, 99.429, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube045_Material067_0.geometry} material={materials['Material.067']}
                    position={[-199.673, 99.429, -151.498]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[3.122, 2.804, 2.606]}/>
              <mesh geometry={nodes.Cube051_Material036_0.geometry} material={materials['Material.036']}
                    position={[-0.072, 251.337, -43.252]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[38.021, 3.513, 3.506]}/>
              <mesh geometry={nodes.Plane_Material039_0.geometry} material={materials['Material.039']}
                    position={[-183.493, 250.872, -10.783]} rotation={[-Math.PI / 2, 0, 0.538]}
                    scale={[28.973, 23.024, 23.024]}/>
              <mesh geometry={nodes.Cylinder_Material040_0.geometry} material={materials['Material.040']}
                    position={[-192.078, 250.872, -5.967]} rotation={[-Math.PI / 2, 0, 0.538]}
                    scale={[2.749, 2.749, 0.516]}/>
              <mesh geometry={nodes.Cylinder001_Material041_0.geometry} material={materials['Material.041']}
                    position={[-192.078, 266.323, -5.967]} rotation={[-Math.PI / 2, 0, 0.538]}
                    scale={[2.177, 2.177, 16]}/>
              <mesh geometry={nodes.Cylinder002_Material048_0.geometry} material={materials['Material.048']}
                    position={[-192.093, 323.055, -5.968]} rotation={[-Math.PI / 2, 0, 0.538]}
                    scale={[3.352, 3.352, 34.096]}/>
              <mesh geometry={nodes.Cylinder003_Material049_0.geometry} material={materials['Material.049']}
                    position={[-192.093, 366.981, -5.968]} rotation={[-Math.PI / 2, 0, 0.538]}
                    scale={[3.352, 3.352, 34.096]}/>
              <mesh geometry={nodes.Cylinder009__0.geometry} material={materials['Cylinder.009__0']}
                    position={[-193.498, 337.077, -8.263]} rotation={[0, 0.538, 0]} scale={[0.629, 0.629, 0.885]}/>
              <mesh geometry={nodes.Cylinder010_Material051_0.geometry} material={materials['Material.051']}
                    position={[-180.617, 337.43, -12.831]} rotation={[0, -1.026, 0]} scale={[1.016, 1.016, 1.758]}/>
              <mesh geometry={nodes.Cylinder011_Material046_0.geometry} material={materials['Material.046']}
                    position={[-178.511, 337.487, -14.077]} rotation={[-Math.PI, 1.028, Math.PI]}
                    scale={[1.747, 1.747, 0.728]}/>
              <mesh geometry={nodes.Cylinder012_Material045_0.geometry} material={materials['Material.045']}
                    position={[-190.098, 337.009, -2.279]} rotation={[0, 0.538, 0]} scale={[1.747, 1.747, 0.728]}/>
              <mesh geometry={nodes.Cylinder013_Material052_0.geometry} material={materials['Material.052']}
                    position={[-173.669, 337.416, -17.092]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[6.461, 6.461, 0.488]}/>
              <mesh geometry={nodes.Cylinder014_Material042_0.geometry} material={materials['Material.042']}
                    position={[-194.447, 337.009, -9.575]} rotation={[0, 0.538, 0]} scale={[1.747, 1.747, 0.728]}/>
              <mesh geometry={nodes.Cylinder015_Material043_0.geometry} material={materials['Material.043']}
                    position={[-194.215, 293.05, -9.714]} rotation={[0, 0.538, 0]} scale={[1.747, 1.747, 0.728]}/>
              <mesh geometry={nodes.Cylinder016_Material044_0.geometry} material={materials['Material.044']}
                    position={[-189.865, 293.05, -2.417]} rotation={[0, 0.538, 0]} scale={[1.747, 1.747, 0.728]}/>
              <mesh geometry={nodes.Cylinder017__0.geometry} material={materials['Cylinder.009__0']}
                    position={[-193.266, 293.117, -8.402]} rotation={[0, 0.538, 0]} scale={[0.629, 0.629, 0.885]}/>
              <mesh geometry={nodes.Cylinder018_Material053_0.geometry} material={materials['Material.053']}
                    position={[-175.403, 292.829, -15.979]} rotation={[-Math.PI / 2, 0, 0]}
                    scale={[4.094, 4.094, 0.309]}/>
              <mesh geometry={nodes.Cylinder019_Material047_0.geometry} material={materials['Material.047']}
                    position={[-178.511, 293.109, -14.077]} rotation={[-Math.PI, 1.028, Math.PI]}
                    scale={[1.747, 1.747, 0.728]}/>
              <mesh geometry={nodes.Cylinder020_Material050_0.geometry} material={materials['Material.050']}
                    position={[-180.617, 293.053, -12.831]} rotation={[0, -1.026, 0]} scale={[1.016, 1.016, 1.758]}/>
              <mesh geometry={nodes.Cylinder004__0.geometry} material={materials['Cylinder.009__0']}
                    position={[-192.135, 251.517, -22.7]} rotation={[0, 0.538, 0]} scale={[0.629, 0.629, 0.885]}/>
              <mesh geometry={nodes.Cylinder005__0.geometry} material={materials['Cylinder.009__0']}
                    position={[-194.276, 251.517, -21.783]} rotation={[0, 0.538, 0]} scale={[0.629, 0.629, 0.885]}/>
              <mesh geometry={nodes.Cylinder006__0.geometry} material={materials['Cylinder.009__0']}
                    position={[-196.465, 251.517, -20.845]} rotation={[0, 0.538, 0]} scale={[0.629, 0.629, 0.885]}/>
              <mesh geometry={nodes.Cylinder007_Material055_0.geometry} material={materials['Material.055']}
                    position={[-173.473, 257.079, -1.692]} rotation={[-Math.PI / 2, 0, 0]} scale={5.99}/>
              <mesh geometry={nodes.Cylinder008_Material054_0.geometry} material={materials['Material.054']}
                    position={[-174.754, 283.337, -16.424]} rotation={[-Math.PI / 2, 0, 0]} scale={5.99}/>
              <mesh geometry={nodes.Cylinder021_Material056_0.geometry} material={materials['Material.056']}
                    position={[-192.548, 254.027, -44.114]} rotation={[-Math.PI / 2, 0, 0]} scale={5.99}/>
              <mesh geometry={nodes['��������������_Material027_0'].geometry} material={materials['Material.027']}
                    position={[-65.323, 249.884, 73.706]} scale={36.735}/>
              <mesh geometry={nodes['��������������001_Material028_0'].geometry} material={materials['Material.028']}
                    position={[-65.323, 249.884, 73.706]} scale={36.735}/>
              <mesh geometry={nodes['��������������002_��������������003_Material029_0'].geometry}
                    material={materials['Material.029']} position={[-65.323, 249.884, 73.706]} scale={36.735}/>
              <mesh geometry={nodes['����������_Material030_0'].geometry} material={materials['Material.030']}
                    position={[-65.323, 249.884, 73.706]} scale={36.735}/>
              <mesh geometry={nodes['��������������003_��������������004_Material031_0'].geometry}
                    material={materials['Material.031']} position={[-65.323, 249.884, 73.706]} scale={36.735}/>
              <mesh geometry={nodes['��������������004_��������������005_Material032_0'].geometry}
                    material={materials['Material.032']} position={[-65.323, 249.884, 73.706]} scale={36.735}/>
              <mesh geometry={nodes['��������������005_��������������006_None_0'].geometry} material={materials.None}
                    position={[-65.323, 249.884, 73.706]} scale={36.735}/>
          </group>
      </group>
  )
});

useGLTF.preload("/models/table_with_books_and_globe/scene.gltf")
