/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: SamuelJamesBate (https://sketchfab.com/SamuelJamesBate)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/theological-book-stack-xb2002-02-8bc80ee72d034d3aaff28ab2083591cf
Title: Theological Book Stack (XB2002-02)
*/

import React, {forwardRef} from 'react'
import {useGLTF} from '@react-three/drei'

export const TheologicalBookStack = forwardRef(function TheologicalBookStack(props, ref) {
    const { nodes, materials } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/theological_book_stack/scene.gltf`)
    return (
        <group ref={ref} {...props} dispose={null}>
            <group scale={0.01}>
                <mesh geometry={nodes.SM_BookGreen3_lambert1_0.geometry} material={materials.lambert1} position={[0, 4.293, 5.493]} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.SM_BookGrey1_lambert1_0.geometry} material={materials.lambert1} position={[0, 4.293, 5.493]} rotation={[-Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.SM_BookBlue3_lambert1_0.geometry} material={materials.lambert1} position={[-2.056, 4.293, 5.493]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
        </group>
    )
});
useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/theological_book_stack/scene.gltf`)
