/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: Blarb (https://sketchfab.com/Blarb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wall-pictures-7016b8389cdc45658bb1399f476fad00
Title: Wall Pictures
*/

import React, {forwardRef} from 'react'
import { useGLTF } from '@react-three/drei'

export const WallPictures = forwardRef(function WallPictures(props, ref) {
    const { nodes, materials } = useGLTF(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/wall_pictures/scene.gltf`)
    return (
        <group ref={ref} {...props} dispose={null}>
            <group scale={0.01}>
                <mesh
                    geometry={nodes.wall_picture_2_wall_picture_2_2k_0.geometry}
                    material={materials.wall_picture_2_2k}
                    position={[0, 4.657, -70.974]}
                    rotation={[0, 0, -0.015]}
                    scale={127.73}
                />
                <mesh
                    geometry={nodes.wall_picture_3_wall_picture_3_0.geometry}
                    material={materials.wall_picture_3}
                    position={[0, 11.88, 70.49]}
                    rotation={[-Math.PI / 2, 0.015, 0]}
                    scale={121.209}
                    onClick={props.onClickCoffeeFrame}
                />
                <mesh geometry={nodes.wall_picture_1_wall_picture_1_2k_0.geometry} material={materials.wall_picture_1_2k} position={[0, -16.537, 0.484]} rotation={[-Math.PI / 2, 0.021, 0]} scale={100} />
            </group>
        </group>
    )
});

useGLTF.preload(`${process.env.NEXT_PUBLIC_BASE_PATH}/models/wall_pictures/scene.gltf`)
