/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bge-clock-3Onrg4AiDhuwWq4FCrxjabAHkT
Title: BGE Clock
*/

import React, {forwardRef, useRef} from 'react'
import { useGLTF } from '@react-three/drei'

// eslint-disable-next-line react/display-name
export const WhiteClock = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/white_clock/scene.gltf")
  return (
      <group {...props} ref={ref} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0.05, 0, 0]}>
            <mesh geometry={nodes.Circle016_0.geometry} material={materials.Uhr_2} />
            <mesh name={"clock-border"} geometry={nodes.Circle016_1.geometry} material={materials.Uhr_2_Rand} />
            <mesh geometry={nodes.Circle016_2.geometry} material={materials.Sec_Zeiger} />
            <mesh geometry={nodes.Circle016_3.geometry} material={materials.min_Zeiger} />
          </group>
          <mesh geometry={nodes.Circle000_0.geometry} material={materials['Uhr_2.001']} rotation={[0.05, 0, 0]} scale={1.016} />
        </group>
      </group>
  )
});

useGLTF.preload("/models/white_clock/scene.gltf")
