/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: FractalSpace (https://sketchfab.com/fractalspace)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bookshelf-e271b784fb9449b78771e21518368ba0
Title: Bookshelf
*/

import React, {forwardRef} from "react"
import { useGLTF } from "@react-three/drei"

export const BookCupboard = forwardRef((props, ref) => {
    const { nodes, materials } = useGLTF("/models/book_cupboard/scene.gltf")
    return (
        <group {...props} dispose={null}>
            <group scale={0.01} ref={ref}>
                <mesh geometry={nodes.Shelf__0.geometry} material={materials.Shelf__0} position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[82.237, 100, 100]} />
                <mesh geometry={nodes.Row_1_Books001_0.geometry} material={materials['Books.001']} position={[75.377, 45.245, 32.143]} scale={314.038} />
                <mesh geometry={nodes.Row_2_Books001_0.geometry} material={materials['Books.001']} position={[2.514, 122.283, 15.905]} scale={[320.988, 295.811, 375.85]} />
                <mesh geometry={nodes.Row_3_Books001_0.geometry} material={materials['Books.001']} position={[-1.864, 191.767, 17.422]} scale={[365.133, 340.994, 340.994]} />
            </group>
        </group>
    )
})

useGLTF.preload("/models/book_cupboard/scene.gltf")
